import { Navigation } from '@/components/navigation'
import { hasLocale, NextIntlClientProvider } from 'next-intl'

import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'
import '../globals.css'
import { client } from '@/sanity/client'
import { NavigationQueryResult } from '@/types/sanity'
import { navigationQuery } from '@/sanity/queries'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

const agrandir = localFont({
  variable: '--font-agrandir',
  src: [
    {
      path: '../../public/fonts/agrandir.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/agrandir-700.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/agrandir-900.otf',
      weight: '900',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: React.ReactNode
  params: Promise<{ locale: string }>
}>) {
  const { locale } = await params

  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  const navigation = await client.fetch<NavigationQueryResult>(
    navigationQuery,
    { language: locale },
  )

  return (
    <html lang={locale}>
      <body className={`${inter.variable} ${agrandir.variable} antialiased`}>
        <NextIntlClientProvider>
          <div className="flex min-h-dvh flex-col">
            <Navigation nav={navigation} />
            <main className="flex flex-1 flex-col gap-16 pb-40 lg:gap-20">
              {children}
            </main>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
