import { Navigation } from '@/components/navigation'

import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'
import './globals.css'
import { client } from '@/sanity/client'
import { NavigationQueryResult } from '@/types/sanity'
import { navigationQuery } from '@/lib/sanity/queries'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

const agrandir = localFont({
  variable: '--font-agrandir',
  src: [
    {
      path: '../public/fonts/agrandir.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/agrandir-700.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/agrandir-900.otf',
      weight: '900',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const navigation = await client.fetch<NavigationQueryResult>(navigationQuery)

  return (
    <html lang="en">
      <body className={`${inter.variable} ${agrandir.variable} antialiased`}>
        <div className="flex min-h-dvh flex-col">
          <Navigation nav={navigation} />
          <main className="flex flex-1 flex-col gap-16 pb-40 pt-20 lg:gap-20">
            {children}
          </main>
        </div>
      </body>
    </html>
  )
}
