import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

const agrandir = localFont({
  variable: '--font-agrandir',
  src: [
    {
      path: '../public/fonts/agrandir.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../public/fonts/agrandir-700.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../public/fonts/agrandir-900.otf',
      weight: '900',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${agrandir.variable} antialiased`}>
        {children}
      </body>
    </html>
  )
}
