/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityVercelProtectionBypass = {
  _id: string
  _type: 'sanity.vercelProtectionBypass'
  _createdAt: string
  _updatedAt: string
  _rev: string
  secret?: string
}

export type TranslationMetadata = {
  _id: string
  _type: 'translation.metadata'
  _createdAt: string
  _updatedAt: string
  _rev: string
  translations?: InternationalizedArrayReference
  schemaTypes?: Array<string>
}

export type InternationalizedArrayReference = Array<
  {
    _key: string
  } & InternationalizedArrayReferenceValue
>

export type NavigationReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'navigation'
}

export type NavigationLinkReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'navigationLink'
}

export type NavigationDropdownReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'navigationDropdown'
}

export type FooterReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'footer'
}

export type FooterColumnReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'footerColumn'
}

export type FooterColumnEmailReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'footerColumnEmail'
}

export type FooterColumnNumberReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'footerColumnNumber'
}

export type FooterColumnTextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'footerColumnText'
}

export type ConfigReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'config'
}

export type PhotoReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'photo'
}

export type ButtonLinkReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'buttonLink'
}

export type ImageBannerReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'imageBanner'
}

export type TextHeroReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'textHero'
}

export type ServiceItemReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'serviceItem'
}

export type ServicesReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'services'
}

export type ClientItemReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'clientItem'
}

export type ClientsReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'clients'
}

export type FlockTalkItemReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'flockTalkItem'
}

export type FlockTalkTeaserReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'flockTalkTeaser'
}

export type ImageTextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'imageText'
}

export type ArticleReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'article'
}

export type SeoReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'seo'
}

export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type PageBuilderReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'pageBuilder'
}

export type ServiceReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'service'
}

export type ProjectReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'project'
}

export type FlockTalkReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'flockTalk'
}

export type InternationalizedArrayReferenceValue = {
  _type: 'internationalizedArrayReferenceValue'
  value?:
    | NavigationReference
    | NavigationLinkReference
    | NavigationDropdownReference
    | FooterReference
    | FooterColumnReference
    | FooterColumnEmailReference
    | FooterColumnNumberReference
    | FooterColumnTextReference
    | ConfigReference
    | PhotoReference
    | ButtonLinkReference
    | ImageBannerReference
    | TextHeroReference
    | ServiceItemReference
    | ServicesReference
    | ClientItemReference
    | ClientsReference
    | FlockTalkItemReference
    | FlockTalkTeaserReference
    | ImageTextReference
    | ArticleReference
    | SeoReference
    | PageReference
    | PageBuilderReference
    | ServiceReference
    | ProjectReference
    | FlockTalkReference
}

export type PageBuilder = Array<
  | ({
      _key: string
    } & TextHero)
  | ({
      _key: string
    } & Services)
  | ({
      _key: string
    } & Clients)
  | ({
      _key: string
    } & FlockTalkTeaser)
  | ({
      _key: string
    } & ImageText)
  | ({
      _key: string
    } & ImageBanner)
  | ({
      _key: string
    } & Article)
>

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Seo = {
  _type: 'seo'
  title?: string
  description?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  keywords?: Array<string>
}

export type Article = {
  _type: 'article'
  text?: Array<
    | ({
        _key: string
      } & Photo)
    | ({
        _key: string
      } & ButtonLink)
  >
  constrained?: boolean
}

export type ImageText = {
  _type: 'imageText'
  title?: string
  text?: Array<
    | ({
        _key: string
      } & Photo)
    | ({
        _key: string
      } & ButtonLink)
  >
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  imageRounded?: boolean
  imagePosition?: 'left' | 'right' | 'top' | 'bottom'
}

export type FlockTalkTeaser = {
  _type: 'flockTalkTeaser'
  title?: string
  subtitle?: string
  cta?: ButtonLink
  items?: Array<
    {
      _key: string
    } & FlockTalkItem
  >
}

export type FlockTalkItem = {
  _type: 'flockTalkItem'
  item?: FlockTalkReference
}

export type Clients = {
  _type: 'clients'
  title?: string
  subtitle?: string
  clients?: Array<
    {
      _key: string
    } & ClientItem
  >
}

export type ClientItem = {
  _type: 'clientItem'
  name?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type Services = {
  _type: 'services'
  services?: Array<
    {
      _key: string
    } & ServiceItem
  >
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type ServiceItem = {
  _type: 'serviceItem'
  name?: string
  link?: ServiceReference
}

export type TextHero = {
  _type: 'textHero'
  title?: string
  description?: string
}

export type ImageBanner = {
  _type: 'imageBanner'
  title?: string
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type ButtonLink = {
  _type: 'buttonLink'
  label?: string
  link?:
    | PageReference
    | ServiceReference
    | ProjectReference
    | FlockTalkReference
  variant?:
    | 'link'
    | 'default'
    | 'destructive'
    | 'outline'
    | 'secondary'
    | 'ghost'
    | 'link'
  size?: 'default' | 'sm' | 'lg'
}

export type Photo = {
  _type: 'photo'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  alt?: string
  aspectRatio?: 'square' | 'landscape' | 'portrait'
  centered?: boolean
}

export type Config = {
  _id: string
  _type: 'config'
  _createdAt: string
  _updatedAt: string
  _rev: string
  navigation?: Navigation
  footer?: Footer
  language?: string
}

export type Footer = {
  _type: 'footer'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  columns?: Array<
    {
      _key: string
    } & FooterColumn
  >
  policies?: Array<
    {
      _key: string
    } & NavigationLink
  >
  linkedIn?: string
  instagram?: string
}

export type Navigation = {
  _type: 'navigation'
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  links?: Array<
    | ({
        _key: string
      } & NavigationLink)
    | ({
        _key: string
      } & NavigationDropdown)
  >
}

export type FooterColumnText = {
  _type: 'footerColumnText'
  text?: string
}

export type FooterColumnNumber = {
  _type: 'footerColumnNumber'
  number?: string
}

export type FooterColumnEmail = {
  _type: 'footerColumnEmail'
  email?: string
}

export type FooterColumn = {
  _type: 'footerColumn'
  name?: string
  columnItems?: Array<
    | ({
        _key: string
      } & FooterColumnNumber)
    | ({
        _key: string
      } & FooterColumnEmail)
    | ({
        _key: string
      } & FooterColumnText)
  >
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type NavigationDropdown = {
  _type: 'navigationDropdown'
  name?: string
  links?: Array<
    {
      _key: string
    } & NavigationLink
  >
}

export type NavigationLink = {
  _type: 'navigationLink'
  name?: string
  page?:
    | PageReference
    | ServiceReference
    | ProjectReference
    | FlockTalkReference
}

export type FlockTalk = {
  _id: string
  _type: 'flockTalk'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  thumbnail?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  content?: PageBuilder
  seo?: Seo
  language?: string
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type Project = {
  _id: string
  _type: 'project'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  content?: PageBuilder
  seo?: Seo
  language?: string
}

export type Service = {
  _id: string
  _type: 'service'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  content?: PageBuilder
  seo?: Seo
  language?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  content?: PageBuilder
  seo?: Seo
  language?: string
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | SanityVercelProtectionBypass
  | TranslationMetadata
  | InternationalizedArrayReference
  | NavigationReference
  | NavigationLinkReference
  | NavigationDropdownReference
  | FooterReference
  | FooterColumnReference
  | FooterColumnEmailReference
  | FooterColumnNumberReference
  | FooterColumnTextReference
  | ConfigReference
  | PhotoReference
  | ButtonLinkReference
  | ImageBannerReference
  | TextHeroReference
  | ServiceItemReference
  | ServicesReference
  | ClientItemReference
  | ClientsReference
  | FlockTalkItemReference
  | FlockTalkTeaserReference
  | ImageTextReference
  | ArticleReference
  | SeoReference
  | PageReference
  | PageBuilderReference
  | ServiceReference
  | ProjectReference
  | FlockTalkReference
  | InternationalizedArrayReferenceValue
  | PageBuilder
  | SanityImageAssetReference
  | Seo
  | Article
  | ImageText
  | FlockTalkTeaser
  | FlockTalkItem
  | Clients
  | ClientItem
  | Services
  | ServiceItem
  | TextHero
  | ImageBanner
  | ButtonLink
  | Photo
  | Config
  | Footer
  | Navigation
  | FooterColumnText
  | FooterColumnNumber
  | FooterColumnEmail
  | FooterColumn
  | SanityImageCrop
  | SanityImageHotspot
  | NavigationDropdown
  | NavigationLink
  | FlockTalk
  | Slug
  | Project
  | Service
  | Page
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

export declare const internalGroqTypeReferenceTo: unique symbol

type ArrayOf<T> = Array<
  T & {
    _key: string
  }
>

// Source: ../web/sanity/queries.ts
// Variable: configQuery
// Query: *[    _type == "config" &&    language == $language  ]{    navigation{      name,      image,      links[]{        ...,        _type == "navigationLink" => {          ...,          page->{ _type, "slug": slug.current }        },        _type == "navigationDropdown" => {          ...,          links[]{            ...,            page->{  _type,  "slug": slug.current}          }        }      }    },    footer{      ...,      policies[]{        ...,        _type == "navigationLink" => {          ...,          page->{ _type, "slug": slug.current }        }      }    }  }[0]
export type ConfigQueryResult = {
  navigation: {
    name: null
    image: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    } | null
    links: Array<
      | {
          _key: string
          _type: 'navigationDropdown'
          name?: string
          links: Array<{
            _key: string
            _type: 'navigationLink'
            name?: string
            page:
              | {
                  _type: 'flockTalk'
                  slug: string | null
                }
              | {
                  _type: 'page'
                  slug: string | null
                }
              | {
                  _type: 'project'
                  slug: string | null
                }
              | {
                  _type: 'service'
                  slug: string | null
                }
              | null
          }> | null
        }
      | {
          _key: string
          _type: 'navigationLink'
          name?: string
          page:
            | {
                _type: 'flockTalk'
                slug: string | null
              }
            | {
                _type: 'page'
                slug: string | null
              }
            | {
                _type: 'project'
                slug: string | null
              }
            | {
                _type: 'service'
                slug: string | null
              }
            | null
        }
    > | null
  } | null
  footer: {
    _type: 'footer'
    image?: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
    }
    columns?: Array<
      {
        _key: string
      } & FooterColumn
    >
    policies: Array<{
      _key: string
      _type: 'navigationLink'
      name?: string
      page:
        | {
            _type: 'flockTalk'
            slug: string | null
          }
        | {
            _type: 'page'
            slug: string | null
          }
        | {
            _type: 'project'
            slug: string | null
          }
        | {
            _type: 'service'
            slug: string | null
          }
        | null
    }> | null
    linkedIn?: string
    instagram?: string
  } | null
} | null

// Source: ../web/sanity/queries.ts
// Variable: pageQuery
// Query: *[    _type in ["page", "service", "project", "flockTalk"] &&     slug.current == $slug &&    language == $language  ][0]{    ...,      content[]{    ...,    _type == "services" => {      ...,      services[]{        ...,        "link": {          "slug": link->slug.current,        }      }    },    _type == "flockTalkTeaser" => {      ...,      cta{        ...,        "link": link->slug.current      },      items[]{        _key,        _type,        "slug": item->slug.current,        "thumbnail": item->thumbnail,        "title": item->title,      }    },    _type == "imageText" => {      ...,      text[]{        ...,        _type == "buttonLink" => {          ...,          "link": link->slug.current        }      }    },    _type == "article" => {      ...,      text[]{        ...,        _type == "buttonLink" => {          ...,          "link": link->slug.current        }      }    },  },    "seo": {      "title": coalesce(seo.title, title, ""),      "description": coalesce(seo.description,  ""),      "image": seo.image,      "keywords": coalesce(seo.keywords, []),    },  }
export type PageQueryResult =
  | {
      _id: string
      _type: 'flockTalk'
      _createdAt: string
      _updatedAt: string
      _rev: string
      title?: string
      slug?: Slug
      thumbnail?: {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
      }
      content: Array<
        | {
            _key: string
            _type: 'article'
            text: Array<
              | {
                  _key: string
                  _type: 'buttonLink'
                  label?: string
                  link: string | null
                  variant?:
                    | 'default'
                    | 'destructive'
                    | 'ghost'
                    | 'link'
                    | 'outline'
                    | 'secondary'
                  size?: 'default' | 'lg' | 'sm'
                }
              | {
                  _key: string
                  _type: 'photo'
                  image?: {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                  }
                  alt?: string
                  aspectRatio?: 'landscape' | 'portrait' | 'square'
                  centered?: boolean
                }
            > | null
            constrained?: boolean
          }
        | {
            _key: string
            _type: 'clients'
            title?: string
            subtitle?: string
            clients?: Array<
              {
                _key: string
              } & ClientItem
            >
          }
        | {
            _key: string
            _type: 'flockTalkTeaser'
            title?: string
            subtitle?: string
            cta: {
              _type: 'buttonLink'
              label?: string
              link: string | null
              variant?:
                | 'default'
                | 'destructive'
                | 'ghost'
                | 'link'
                | 'outline'
                | 'secondary'
              size?: 'default' | 'lg' | 'sm'
            } | null
            items: Array<{
              _key: string
              _type: 'flockTalkItem'
              slug: string | null
              thumbnail: {
                asset?: SanityImageAssetReference
                media?: unknown
                hotspot?: SanityImageHotspot
                crop?: SanityImageCrop
                _type: 'image'
              } | null
              title: string | null
            }> | null
          }
        | {
            _key: string
            _type: 'imageBanner'
            title?: string
            image?: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
            }
          }
        | {
            _key: string
            _type: 'imageText'
            title?: string
            text: Array<
              | {
                  _key: string
                  _type: 'buttonLink'
                  label?: string
                  link: string | null
                  variant?:
                    | 'default'
                    | 'destructive'
                    | 'ghost'
                    | 'link'
                    | 'outline'
                    | 'secondary'
                  size?: 'default' | 'lg' | 'sm'
                }
              | {
                  _key: string
                  _type: 'photo'
                  image?: {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                  }
                  alt?: string
                  aspectRatio?: 'landscape' | 'portrait' | 'square'
                  centered?: boolean
                }
            > | null
            image?: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
            }
            imageRounded?: boolean
            imagePosition?: 'bottom' | 'left' | 'right' | 'top'
          }
        | {
            _key: string
            _type: 'services'
            services: Array<{
              _key: string
              _type: 'serviceItem'
              name?: string
              link: {
                slug: string | null
              }
            }> | null
            image?: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
            }
          }
        | {
            _key: string
            _type: 'textHero'
            title?: string
            description?: string
          }
      > | null
      seo: {
        title: string | ''
        description: string | ''
        image: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
        keywords: Array<string> | Array<never>
      }
      language?: string
    }
  | {
      _id: string
      _type: 'page'
      _createdAt: string
      _updatedAt: string
      _rev: string
      title?: string
      slug?: Slug
      content: Array<
        | {
            _key: string
            _type: 'article'
            text: Array<
              | {
                  _key: string
                  _type: 'buttonLink'
                  label?: string
                  link: string | null
                  variant?:
                    | 'default'
                    | 'destructive'
                    | 'ghost'
                    | 'link'
                    | 'outline'
                    | 'secondary'
                  size?: 'default' | 'lg' | 'sm'
                }
              | {
                  _key: string
                  _type: 'photo'
                  image?: {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                  }
                  alt?: string
                  aspectRatio?: 'landscape' | 'portrait' | 'square'
                  centered?: boolean
                }
            > | null
            constrained?: boolean
          }
        | {
            _key: string
            _type: 'clients'
            title?: string
            subtitle?: string
            clients?: Array<
              {
                _key: string
              } & ClientItem
            >
          }
        | {
            _key: string
            _type: 'flockTalkTeaser'
            title?: string
            subtitle?: string
            cta: {
              _type: 'buttonLink'
              label?: string
              link: string | null
              variant?:
                | 'default'
                | 'destructive'
                | 'ghost'
                | 'link'
                | 'outline'
                | 'secondary'
              size?: 'default' | 'lg' | 'sm'
            } | null
            items: Array<{
              _key: string
              _type: 'flockTalkItem'
              slug: string | null
              thumbnail: {
                asset?: SanityImageAssetReference
                media?: unknown
                hotspot?: SanityImageHotspot
                crop?: SanityImageCrop
                _type: 'image'
              } | null
              title: string | null
            }> | null
          }
        | {
            _key: string
            _type: 'imageBanner'
            title?: string
            image?: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
            }
          }
        | {
            _key: string
            _type: 'imageText'
            title?: string
            text: Array<
              | {
                  _key: string
                  _type: 'buttonLink'
                  label?: string
                  link: string | null
                  variant?:
                    | 'default'
                    | 'destructive'
                    | 'ghost'
                    | 'link'
                    | 'outline'
                    | 'secondary'
                  size?: 'default' | 'lg' | 'sm'
                }
              | {
                  _key: string
                  _type: 'photo'
                  image?: {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                  }
                  alt?: string
                  aspectRatio?: 'landscape' | 'portrait' | 'square'
                  centered?: boolean
                }
            > | null
            image?: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
            }
            imageRounded?: boolean
            imagePosition?: 'bottom' | 'left' | 'right' | 'top'
          }
        | {
            _key: string
            _type: 'services'
            services: Array<{
              _key: string
              _type: 'serviceItem'
              name?: string
              link: {
                slug: string | null
              }
            }> | null
            image?: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
            }
          }
        | {
            _key: string
            _type: 'textHero'
            title?: string
            description?: string
          }
      > | null
      seo: {
        title: string | ''
        description: string | ''
        image: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
        keywords: Array<string> | Array<never>
      }
      language?: string
    }
  | {
      _id: string
      _type: 'project'
      _createdAt: string
      _updatedAt: string
      _rev: string
      title?: string
      slug?: Slug
      content: Array<
        | {
            _key: string
            _type: 'article'
            text: Array<
              | {
                  _key: string
                  _type: 'buttonLink'
                  label?: string
                  link: string | null
                  variant?:
                    | 'default'
                    | 'destructive'
                    | 'ghost'
                    | 'link'
                    | 'outline'
                    | 'secondary'
                  size?: 'default' | 'lg' | 'sm'
                }
              | {
                  _key: string
                  _type: 'photo'
                  image?: {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                  }
                  alt?: string
                  aspectRatio?: 'landscape' | 'portrait' | 'square'
                  centered?: boolean
                }
            > | null
            constrained?: boolean
          }
        | {
            _key: string
            _type: 'clients'
            title?: string
            subtitle?: string
            clients?: Array<
              {
                _key: string
              } & ClientItem
            >
          }
        | {
            _key: string
            _type: 'flockTalkTeaser'
            title?: string
            subtitle?: string
            cta: {
              _type: 'buttonLink'
              label?: string
              link: string | null
              variant?:
                | 'default'
                | 'destructive'
                | 'ghost'
                | 'link'
                | 'outline'
                | 'secondary'
              size?: 'default' | 'lg' | 'sm'
            } | null
            items: Array<{
              _key: string
              _type: 'flockTalkItem'
              slug: string | null
              thumbnail: {
                asset?: SanityImageAssetReference
                media?: unknown
                hotspot?: SanityImageHotspot
                crop?: SanityImageCrop
                _type: 'image'
              } | null
              title: string | null
            }> | null
          }
        | {
            _key: string
            _type: 'imageBanner'
            title?: string
            image?: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
            }
          }
        | {
            _key: string
            _type: 'imageText'
            title?: string
            text: Array<
              | {
                  _key: string
                  _type: 'buttonLink'
                  label?: string
                  link: string | null
                  variant?:
                    | 'default'
                    | 'destructive'
                    | 'ghost'
                    | 'link'
                    | 'outline'
                    | 'secondary'
                  size?: 'default' | 'lg' | 'sm'
                }
              | {
                  _key: string
                  _type: 'photo'
                  image?: {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                  }
                  alt?: string
                  aspectRatio?: 'landscape' | 'portrait' | 'square'
                  centered?: boolean
                }
            > | null
            image?: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
            }
            imageRounded?: boolean
            imagePosition?: 'bottom' | 'left' | 'right' | 'top'
          }
        | {
            _key: string
            _type: 'services'
            services: Array<{
              _key: string
              _type: 'serviceItem'
              name?: string
              link: {
                slug: string | null
              }
            }> | null
            image?: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
            }
          }
        | {
            _key: string
            _type: 'textHero'
            title?: string
            description?: string
          }
      > | null
      seo: {
        title: string | ''
        description: string | ''
        image: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
        keywords: Array<string> | Array<never>
      }
      language?: string
    }
  | {
      _id: string
      _type: 'service'
      _createdAt: string
      _updatedAt: string
      _rev: string
      title?: string
      slug?: Slug
      content: Array<
        | {
            _key: string
            _type: 'article'
            text: Array<
              | {
                  _key: string
                  _type: 'buttonLink'
                  label?: string
                  link: string | null
                  variant?:
                    | 'default'
                    | 'destructive'
                    | 'ghost'
                    | 'link'
                    | 'outline'
                    | 'secondary'
                  size?: 'default' | 'lg' | 'sm'
                }
              | {
                  _key: string
                  _type: 'photo'
                  image?: {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                  }
                  alt?: string
                  aspectRatio?: 'landscape' | 'portrait' | 'square'
                  centered?: boolean
                }
            > | null
            constrained?: boolean
          }
        | {
            _key: string
            _type: 'clients'
            title?: string
            subtitle?: string
            clients?: Array<
              {
                _key: string
              } & ClientItem
            >
          }
        | {
            _key: string
            _type: 'flockTalkTeaser'
            title?: string
            subtitle?: string
            cta: {
              _type: 'buttonLink'
              label?: string
              link: string | null
              variant?:
                | 'default'
                | 'destructive'
                | 'ghost'
                | 'link'
                | 'outline'
                | 'secondary'
              size?: 'default' | 'lg' | 'sm'
            } | null
            items: Array<{
              _key: string
              _type: 'flockTalkItem'
              slug: string | null
              thumbnail: {
                asset?: SanityImageAssetReference
                media?: unknown
                hotspot?: SanityImageHotspot
                crop?: SanityImageCrop
                _type: 'image'
              } | null
              title: string | null
            }> | null
          }
        | {
            _key: string
            _type: 'imageBanner'
            title?: string
            image?: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
            }
          }
        | {
            _key: string
            _type: 'imageText'
            title?: string
            text: Array<
              | {
                  _key: string
                  _type: 'buttonLink'
                  label?: string
                  link: string | null
                  variant?:
                    | 'default'
                    | 'destructive'
                    | 'ghost'
                    | 'link'
                    | 'outline'
                    | 'secondary'
                  size?: 'default' | 'lg' | 'sm'
                }
              | {
                  _key: string
                  _type: 'photo'
                  image?: {
                    asset?: SanityImageAssetReference
                    media?: unknown
                    hotspot?: SanityImageHotspot
                    crop?: SanityImageCrop
                    _type: 'image'
                  }
                  alt?: string
                  aspectRatio?: 'landscape' | 'portrait' | 'square'
                  centered?: boolean
                }
            > | null
            image?: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
            }
            imageRounded?: boolean
            imagePosition?: 'bottom' | 'left' | 'right' | 'top'
          }
        | {
            _key: string
            _type: 'services'
            services: Array<{
              _key: string
              _type: 'serviceItem'
              name?: string
              link: {
                slug: string | null
              }
            }> | null
            image?: {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              alt?: string
              _type: 'image'
            }
          }
        | {
            _key: string
            _type: 'textHero'
            title?: string
            description?: string
          }
      > | null
      seo: {
        title: string | ''
        description: string | ''
        image: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        } | null
        keywords: Array<string> | Array<never>
      }
      language?: string
    }
  | null

// Source: ../web/sanity/queries.ts
// Variable: sitemapQuery
// Query: *[    _type in ["page", "service", "project", "flockTalk"] &&    defined(slug.current)  ] {    "href": slug.current,    _updatedAt,    language,  }
export type SitemapQueryResult = Array<{
  href: string | null
  _updatedAt: string
  language: string | null
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '\n  *[\n    _type == "config" &&\n    language == $language\n  ]{\n    navigation{\n      name,\n      image,\n      links[]{\n        ...,\n        _type == "navigationLink" => {\n          ...,\n          page->{ _type, "slug": slug.current }\n        },\n        _type == "navigationDropdown" => {\n          ...,\n          links[]{\n            ...,\n            page->{\n  _type,\n  "slug": slug.current\n}\n          }\n        }\n      }\n    },\n    footer{\n      ...,\n      policies[]{\n        ...,\n        _type == "navigationLink" => {\n          ...,\n          page->{ _type, "slug": slug.current }\n        }\n      }\n    }\n  }[0]\n': ConfigQueryResult
    '\n  *[\n    _type in ["page", "service", "project", "flockTalk"] && \n    slug.current == $slug &&\n    language == $language\n  ][0]{\n    ...,\n    \n  content[]{\n    ...,\n    _type == "services" => {\n      ...,\n      services[]{\n        ...,\n        "link": {\n          "slug": link->slug.current,\n        }\n      }\n    },\n    _type == "flockTalkTeaser" => {\n      ...,\n      cta{\n        ...,\n        "link": link->slug.current\n      },\n      items[]{\n        _key,\n        _type,\n        "slug": item->slug.current,\n        "thumbnail": item->thumbnail,\n        "title": item->title,\n      }\n    },\n    _type == "imageText" => {\n      ...,\n      text[]{\n        ...,\n        _type == "buttonLink" => {\n          ...,\n          "link": link->slug.current\n        }\n      }\n    },\n    _type == "article" => {\n      ...,\n      text[]{\n        ...,\n        _type == "buttonLink" => {\n          ...,\n          "link": link->slug.current\n        }\n      }\n    },\n  },\n\n    "seo": {\n      "title": coalesce(seo.title, title, ""),\n      "description": coalesce(seo.description,  ""),\n      "image": seo.image,\n      "keywords": coalesce(seo.keywords, []),\n    },\n  }\n': PageQueryResult
    '\n  *[\n    _type in ["page", "service", "project", "flockTalk"] &&\n    defined(slug.current)\n  ] {\n    "href": slug.current,\n    _updatedAt,\n    language,\n  }\n': SitemapQueryResult
  }
}
