import { Navigation } from '@/components/navigation'
import { hasLocale, NextIntlClientProvider } from 'next-intl'

import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { Inter } from 'next/font/google'
import '../globals.css'
import { sanityFetch } from '@/sanity/client'
import { NavigationQueryResult } from '@/types/sanity'
import { navigationQuery } from '@/sanity/queries'
import { notFound } from 'next/navigation'
import { routing } from '@/i18n/routing'
import { VisualEditing } from 'next-sanity/visual-editing'
import { draftMode } from 'next/headers'
import { DisableDraftMode } from '@/components/disable-draft-mode'

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
})

const agrandir = localFont({
  variable: '--font-agrandir',
  src: [
    {
      path: '../../public/fonts/agrandir.otf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../../public/fonts/agrandir-700.otf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../../public/fonts/agrandir-900.otf',
      weight: '900',
      style: 'normal',
    },
  ],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params,
}: LayoutProps<'/[[...slug]]'>) {
  const { isEnabled } = await draftMode()
  const { slug } = await params
  const [locale] = slug || [routing.defaultLocale]

  if (!hasLocale(routing.locales, locale)) {
    notFound()
  }

  const navigation = await sanityFetch<NavigationQueryResult>({
    query: navigationQuery,
    params: { language: locale },
  })

  return (
    <html lang={locale}>
      <body className={`${inter.variable} ${agrandir.variable} antialiased`}>
        <NextIntlClientProvider>
          <div className="flex min-h-dvh flex-col">
            <Navigation nav={navigation} />
            <main className="flex flex-1 flex-col gap-16 pb-40 lg:gap-20">
              {children}
              {isEnabled && (
                <>
                  <VisualEditing />
                  <DisableDraftMode />
                </>
              )}
            </main>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
